#!/usr/bin/python
# Nagios plugin to check the system state according to systemd.

from __future__ import division, print_function
import subprocess
import sys

try:
    state = subprocess.check_output(['systemctl', 'is-system-running'])
    state = state.strip()
except subprocess.CalledProcessError as e:
    state = e.output.strip()
    print('System NOT OK: {}'.format(state))
    sys.exit(2)

if state == 'running':
    print('System OK: {}'.format(state))
    sys.exit(0)
else:
    print('System NOT OK: {}'.format(state))
    sys.exit(0)
