#!/usr/bin/python
# Nagios plugin to check the system state according to systemd.

from __future__ import division, print_function
import posixpath
import subprocess
import sys


def find_systemctl():
    systemctls = [ '/bin/systemctl', '/usr/bin/systemctl' ]
    for systemctl in systemctls:
        if posixpath.exists(systemctl):
            return systemctl


systemctl = find_systemctl()
if not systemctl:
    print('System WARN: systemctl not found')
    sys.exit(1)

try:
    state = subprocess.check_output([systemctl, 'is-system-running'])
    state = state.strip()
except subprocess.CalledProcessError as e:
    state = e.output.strip()
    print('System NOT OK: {}'.format(state))
    sys.exit(2)

if state in ['running', 'starting']:
    print('System OK: {}'.format(state))
    sys.exit(0)
else:
    print('System NOT OK: {}'.format(state))
    sys.exit(0)
